export const AUDIT_ACTIONS = {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    LOGIN_FAILED: "LOGIN_FAILED",

    UPLOAD_FILE: "UPLOAD_FILE",
    DOWNLOAD_FILE: "DOWNLOAD_FILE",
    DELETE_FILE: "DELETE_FILE",

    CREATE_SHARE: "CREATE_SHARE",
    DOWNLOAD_SHARE: "DOWNLOAD_SHARE",
    REVOKE_SHARE: "REVOKE_SHARE",

    INVALID_SHARE: "INVALID_SHARE",
    EXPIRED_SHARE: "EXPIRED_SHARE",
    PASSWORD_FAILED: "PASSWORD_FAILED"
};

export const AUDIT_STATUS = {
    SUCCESS: "SUCCESS",
    FAILED: "FAILED"
};

export const RESOURCE_TYPES = {
    FILE: "FILE",
    SHARE: "SHARE",
    USER: "USER"
};